### ISSUE TITLE
Trying to build example on current Defold version

### ISSUE THREAD

**Issue by subsoap** [britzl/steamworks-defold#7]
![2019-02-11 15_00_30-defold editor 2 0 - steamworks](https://user-images.githubusercontent.com/409170/52599564-dbe23b80-2e0d-11e9-9bd1-d5c136be9156.png)

build/main_tmpa036c992-2317-4050-9a76-8f26a594bc8e.o: undefined symbol: steamworks

**Comment by subsoap** [comment]
This version builds https://github.com/britzl/steamworks-defold/tree/fd07c3e5fe9d567cd015a257160fc1459164d104

**Comment by subsoap** [comment]
Probably needs a structure closer to this https://github.com/subsoap/vibrate/blob/master/vibrate/src/extension.cpp

**Comment by subsoap** [comment]
Got latest building, had to edit auto generated file so you will need to change the template or something. Also there is a change you did to extension.cpp which I had to revert it needs to be "lld" for whatever reason not "ld" it's possible "ld" is correct for it to work somewhere but then it's wrong elsewhere too as it will not build without "lld".

![2019-02-11 15_42_36-don t declare the extension on mobile and web britzl_steamworks-defold 2bd42a9](https://user-images.githubusercontent.com/409170/52601438-ab9d9b80-2e13-11e9-8717-c8c93311e883.png)

Check bottom and top for changes

[extension.zip](https://github.com/britzl/steamworks-defold/files/2853468/extension.zip)

**Comment by britzl** [comment]
On which platform does it refuse to build with %ld?

**Comment by subsoap** [comment]
Windows 10

**Comment by britzl** [comment]
Hmm, ok, I'm perfectly able to bundle for Windows (32 and 64 bit) from OSX. What kind of error are you getting?

**Comment by britzl** [comment]
Umm, it seems like it should be DM_PLATFORM_WINDOWS and not DM_PLATFORM_WIN32! Need to investigate further.

**Comment by subsoap** [comment]
Did you check my included extension.zip posted previously? I did change it to DM_PLATFORM_WINDOWS I guess the docs are wrong but other extensions have had it right for a while or something.

**Comment by subsoap** [comment]
If you make a version which builds fine with %ld put it on a branch and I'll test to see if it builds for me.

**Comment by britzl** [comment]
There were a couple of issues with platform detection. My noobishness with C made me blind to this:

#ifdef DM_PLATFORM_OSX || DM_PLATFORM_WINDOWS || DM_PLATFORM_LINUX

Will never properly evaluate. It should be:

#if defined(DM_PLATFORM_OSX) || defined(DM_PLATFORM_WINDOWS) || defined(DM_PLATFORM_LINUX)

And the platform constant for windows should be DM_PLATFORM_WINDOWS and not DM_PLATFORM_WIN32. This will be fixed in our documentation.

Also, for now Linux is not working. I'm waiting for a fix from Mathias to support any dynamic lib on Linux. Will hopefully be released in 1.2.147.

**Comment by britzl** [comment]
Closing this one. Linux issue is reported in #8
